[phases.setup]
aptPkgs = [
  "ffmpeg",
  "python3",
  "python3-pip",
  "yt-dlp",
  "libnss3",
  "libatk1.0-0",
  "libatk-bridge2.0-0",
  "libxkbcommon0",
  "libgtk-3-0",
  "libgbm1",
  "libasound2t64",
  "libnspr4"
]

[phases.install]
cmds = [
  "yarn install --no-frozen-lockfile"
]
